/xyz/openbmc_project/inventory/system:
  sensorID: 0x0
  sensorType: 0x12
  eventReadingType: 0x6F
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/BMC_Module/critical_high:
  sensorID: 0x01
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/BMC_Module/critical_low:
  sensorID: 0x01
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/BMC_Module/warning_high:
  sensorID: 0x01
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/temperature/BMC_Module/warning_low:
  sensorID: 0x01
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/temperature/inlet/critical_high:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/inlet/critical_low:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/inlet/warning_high:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/temperature/inlet/warning_low:
  sensorID: 0x02
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/temperature/outlet/critical_high:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/outlet/critical_low:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/outlet/warning_high:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/temperature/outlet/warning_low:
  sensorID: 0x03
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/temperature/MB0_Temp/critical_high:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/MB0_Temp/critical_low:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/MB0_Temp/warning_high:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/temperature/MB0_Temp/warning_low:
  sensorID: 0x04
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/temperature/P12V_BRIC_Temp/critical_high:
  sensorID: 0x44
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/temperature/P12V_BRIC_Temp/critical_low:
  sensorID: 0x44
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/temperature/P12V_BRIC_Temp/warning_high:
  sensorID: 0x44
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/temperature/P12V_BRIC_Temp/warning_low:
  sensorID: 0x44
  sensorType: 0x01
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/voltage/p0_dimm_vr0_voltage/critical_high:
  sensorID: 0x14
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p0_dimm_vr0_voltage/critical_low:
  sensorID: 0x14
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p0_dimm_vr1_voltage/critical_high:
  sensorID: 0x15
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p0_dimm_vr1_voltage/critical_low:
  sensorID: 0x15
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p1_dimm_vr0_voltage/critical_high:
  sensorID: 0x16
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p1_dimm_vr0_voltage/critical_low:
  sensorID: 0x16
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p1_dimm_vr1_voltage/critical_high:
  sensorID: 0x17
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p1_dimm_vr1_voltage/critical_low:
  sensorID: 0x17
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p0_vccin_vr_voltage/critical_high:
  sensorID: 0x34
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p0_vccin_vr_voltage/critical_low:
  sensorID: 0x34
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p0_vccio_vr_voltage/critical_high:
  sensorID: 0x35
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p0_vccio_vr_voltage/critical_low:
  sensorID: 0x35
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p1_vccin_vr_voltage/critical_high:
  sensorID: 0x36
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p1_vccin_vr_voltage/critical_low:
  sensorID: 0x36
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/p1_vccio_vr_voltage/critical_high:
  sensorID: 0x37
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/p1_vccio_vr_voltage/critical_low:
  sensorID: 0x37
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/P12V_BRIC_Vol/critical_high:
  sensorID: 0x45
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/voltage/P12V_BRIC_Vol/critical_low:
  sensorID: 0x45
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/voltage/P12V_BRIC_Vol/warning_high:
  sensorID: 0x45
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/voltage/P12V_BRIC_Vol/warning_low:
  sensorID: 0x45
  sensorType: 0x02
  eventReadingType: 0x01
  offset: 0x00
/xyz/openbmc_project/sensors/current/P12V_BRIC_Curr/critical_high:
  sensorID: 0x46
  sensorType: 0x03
  eventReadingType: 0x01
  offset: 0x09
/xyz/openbmc_project/sensors/current/P12V_BRIC_Curr/critical_low:
  sensorID: 0x46
  sensorType: 0x03
  eventReadingType: 0x01
  offset: 0x02
/xyz/openbmc_project/sensors/current/P12V_BRIC_Curr/warning_high:
  sensorID: 0x46
  sensorType: 0x03
  eventReadingType: 0x01
  offset: 0x01
/xyz/openbmc_project/sensors/current/P12V_BRIC_Curr/warning_low:
  sensorID: 0x46
  sensorType: 0x03
  eventReadingType: 0x01
  offset: 0x00
